@gtm_mgmt = 192.168.1.146:8443
@tenant_name = MyTenant
@app_name = MyApp
@service_name = MyService

###

POST https://{{gtm_mgmt}}/mgmt/shared/appsvcs/declare
Authorization: Basic admin admin
Content-Type: application/json

{
    "class": "ADC",
    "schemaVersion": "3.9.0",
    "id": "{{tenant_name}}",
    "label": "{{tenant_name}} GSLB Configuration",
    "remark": "GSLB Configuration",
    "controls": {
        "class": "Controls",
        "trace": true,
        "logLevel": "debug"
    },
    "{{tenant_name}}": {
        "class": "Tenant",
        "{{app_name}}": {
            "class": "Application",
            "template": "generic",
            "label": "{{app_name}} pool",
            "{{service_name}}": {
                "class": "GSLB_Pool",
                "resourceRecordType": "A",
                "enabled": true,
                "verifyMemberEnabled": true,
                "members": [
                    {
                        "server": {
                            "bigip": "/Common/bigipa"
                        },
                        "virtualServer": "/{{tenant_name}}/{{app_name}}/{{service_name}}"
                    }
                ],
                "monitors": [
                    {
                        "bigip": "/Common/bigip"
                    }
                ]
            }
        }
    }
}