@gtm_mgmt = 192.168.1.146:8443
@tenant_name = ssh
@service_name = ssh

###

POST https://{{gtm_mgmt}}/mgmt/shared/appsvcs/declare
Authorization: Basic admin admin
Content-Type: application/json

{
    "class": "ADC",
    "schemaVersion": "3.9.0",
    "id": "{{tenant_name}}_domain",
    "label": "{{tenant_name}} GSLB Configuration",
    "remark": "GSLB Configuration",
    "controls": {
        "class": "Controls",
        "trace": true,
        "logLevel": "debug"
    },
    "{{tenant_name}}_domain": {
        "class": "Tenant",
        "label": "{{tenant_name}} domain",
        "{{tenant_name}}_domain": {
            "class": "Application",
            "template": "generic",
            "{{service_name}}_app": {
                "class": "GSLB_Domain",
                "domainName": "ssh.lab.local",
                "resourceRecordType": "A",
                "enabled": true
            }
        }
    }
}