@bigip_mgmt = 0e4bf29c-cb17-4ffc-94bb-cf0b2423db38.access.udf.f5.com
@regKey = SDIFH-ZADYF-YDYGR-DMWMD-PYJGFLY
###

POST https://{{bigip_mgmt}}/mgmt/shared/declarative-onboarding
Authorization: Basic admin admin
Content-Type: application/json

{
    "declaration": {
        "schemaVersion": "1.0.0",
        "class": "Device",
        "label": "BIG-IP LTM",
        "Common": {
            "class": "Tenant",
            "hostname": "ltm1.lab.local",
            "myLicense": {
                "class": "License",
                "licenseType": "regKey",
                "regKey": "{{regKey}}"
            },
            "myDns": {
                "class": "DNS",
                "nameServers": [
                    "8.8.8.8"
                ],
                "search": [
                    "lab.local"
                ]
            },
            "myNtp": {
                "class": "NTP",
                "servers": [
                    "0.pool.ntp.org"
                ],
                "timezone": "CST"
            },
            "myProvisioning": {
                "class": "Provision",
                "ltm": "nominal"
            },
            "internal": {
                "class": "VLAN",
                "tag": 4093,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": false
                    }
                ]
            },
            "internal-self": {
                "class": "SelfIp",
                "address": "10.1.20.4/24",
                "vlan": "internal",
                "allowService": "default",
                "trafficGroup": "traffic-group-local-only"
            },
            "external": {
                "class": "VLAN",
                "tag": 4094,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": false
                    }
                ]
            },
            "external-self": {
                "class": "SelfIp",
                "address": "10.1.10.4/24",
                "vlan": "external",
                "allowService": "none",
                "trafficGroup": "traffic-group-local-only"
            }
        }
    }
}