version: "3.2"

services:
  f5-demo-http:
    image: f5devcentral/f5-demo-httpd
    container_name: f5-demo-httpd
    restart: unless-stopped
    ports:
      - "10.1.20.11:80:80"
      - "10.1.20.11:81:80"
      - "10.1.20.11:82:80"
      - "10.1.20.11:83:80"
    environment:
      - F5DEMO_APP=website
      - F5DEMO_NODENAME='No SSL'
      - F5DEMO_COLOR=ffd734
