version: "3.2"

services:
  graphite-statsd:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

