version: "3.2"

services:
  graphite-statsd:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"
      - "8080:8080"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

