---
- name: 'Install Docker'
  hosts: 'all'
  gather_facts: false

  vars:
    packages:
      - 'docker.io'
      - 'docker-compose'

  tasks:
    - debug: var=inventory_hostname
    - debug: var=ansible_hostname
    - debug: var=ansible_user
    - debug: var=username

    - name: 'Update all packages to the latest version'
      apt:
        update_cache: 'yes'
        upgrade: 'dist'

    - name: 'Install packages'
      apt:
        name: "{{ packages }}"
