version: "3.2"

services:
  as3_container:
    image: f5devcentral/f5-as3-container:latest
    container_name: as3_container
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"

  do_container:
    image: f5devcentral/f5-do-container:latest
    container_name: do_container
    restart: unless-stopped
    ports:
      - "8001:80"
      - "8444:443"
